import { createHash } from 'node:crypto';
import { readFile, readdir, mkdir, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import MarkdownIt from 'markdown-it';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT_DIR = path.join(ROOT, 'content', 'blog');
const BLOG_DIR = path.join(ROOT, 'blog');
const SITE_URL = 'https://www.duniaops.com';
const GENERATED_MARKER = '<!-- Generated by scripts/build-blog.mjs; do not edit. -->';
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const IMAGE_PATTERN = /^\/assets\/blog\/[^?#]+\.(?:jpe?g|png)$/i;

const CATEGORIES = {
  'ai-accelerated-development': {
    label: 'AI-Accelerated Development',
    serviceUrl: '/services/ai-software-development',
    ctaTitle: 'Turn your software idea into a production product',
    ctaText: 'DuniaOps combines senior engineering judgment with AI-accelerated delivery to build reliable software in weeks, not months.'
  },
  'booking-allocation-platforms': {
    label: 'Booking & Allocation Platforms',
    serviceUrl: '/services/booking-and-allocation-systems',
    ctaTitle: 'Need a better booking or allocation platform?',
    ctaText: 'We design and build dependable systems for scheduling, capacity, availability, payments, and operational workflows.'
  },
  'devops-cloud-consultancy': {
    label: 'DevOps & Cloud Consultancy',
    serviceUrl: '/services/devops-and-cloud-consultancy',
    ctaTitle: 'Make your delivery platform faster and safer',
    ctaText: 'DuniaOps helps teams improve cloud architecture, deployment automation, reliability, security, and engineering flow.'
  },
  'mobile-app-development': {
    label: 'Mobile App Development',
    serviceUrl: '/services/mobile-app-development',
    ctaTitle: 'Put a useful mobile product in customers’ hands',
    ctaText: 'We take mobile products from focused first release to reliable production app, with senior engineers throughout.'
  },
  'software-consultancy': {
    label: 'Software Consultancy',
    serviceUrl: '/services/software-consultancy',
    ctaTitle: 'Get senior engineering help on the right problem',
    ctaText: 'DuniaOps brings practical technical leadership to architecture, delivery, modernisation, and complex software decisions.'
  }
};

const STATIC_ROUTES = new Set([
  '/',
  '/blog',
  '/feed.xml',
  '/privacy',
  '/products',
  '/products/rockimals',
  '/products/zoday',
  '/products/lumo',
  '/thank-you',
  '/services/ai-software-development',
  '/services/booking-and-allocation-systems',
  '/services/devops-and-cloud-consultancy',
  '/services/mobile-app-development',
  '/services/software-consultancy'
]);

function escapeHtml(value = '') {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function escapeXml(value = '') {
  return escapeHtml(value);
}

function jsonForHtml(value) {
  return JSON.stringify(value, null, 2).replaceAll('<', '\\u003c');
}

function absoluteUrl(value) {
  return new URL(value, SITE_URL).href;
}

function formatDate(value, field, source) {
  let raw = value;
  if (value instanceof Date && !Number.isNaN(value.valueOf())) {
    raw = value.toISOString().slice(0, 10);
  }
  if (typeof raw !== 'string' || !DATE_PATTERN.test(raw)) {
    throw new Error(`${source}: "${field}" must use YYYY-MM-DD.`);
  }
  const parsed = new Date(`${raw}T00:00:00Z`);
  if (Number.isNaN(parsed.valueOf()) || parsed.toISOString().slice(0, 10) !== raw) {
    throw new Error(`${source}: "${field}" is not a valid calendar date.`);
  }
  return raw;
}

function displayDate(value) {
  return new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC'
  }).format(new Date(`${value}T00:00:00Z`));
}

function wordsIn(markdown) {
  const plain = markdown
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`[^`]*`/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/[#>*_~|-]/g, ' ');
  return plain.match(/[\p{L}\p{N}][\p{L}\p{N}’'-]*/gu)?.length ?? 0;
}

function headingSlug(value) {
  return value
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'section';
}

function renderMarkdown(markdown, source) {
  const toc = [];
  const usedHeadingIds = new Map();
  const md = new MarkdownIt({
    html: false,
    linkify: true,
    typographer: true
  });

  const defaultHeadingOpen = md.renderer.rules.heading_open
    ?? ((tokens, index, options, env, renderer) => renderer.renderToken(tokens, index, options));
  md.renderer.rules.heading_open = (tokens, index, options, env, renderer) => {
    const token = tokens[index];
    const inline = tokens[index + 1];
    const label = inline?.content?.trim() || 'Section';
    const base = headingSlug(label);
    const seen = usedHeadingIds.get(base) ?? 0;
    usedHeadingIds.set(base, seen + 1);
    const id = seen ? `${base}-${seen + 1}` : base;
    token.attrSet('id', id);
    if (token.tag === 'h2') toc.push({ id, label });
    return defaultHeadingOpen(tokens, index, options, env, renderer);
  };

  const defaultImage = md.renderer.rules.image
    ?? ((tokens, index, options, env, renderer) => renderer.renderToken(tokens, index, options));
  md.renderer.rules.image = (tokens, index, options, env, renderer) => {
    tokens[index].attrSet('loading', 'lazy');
    tokens[index].attrSet('decoding', 'async');
    return defaultImage(tokens, index, options, env, renderer);
  };

  for (const match of markdown.matchAll(/!\[([^\]]*)\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)/g)) {
    if (!match[1].trim()) {
      throw new Error(`${source}: every Markdown image must have alternative text.`);
    }
    const target = match[2];
    if (!/^https?:\/\//i.test(target) && !target.startsWith('/assets/')) {
      throw new Error(`${source}: local Markdown images must use a root-relative /assets/ path.`);
    }
  }

  return { html: md.render(markdown), toc };
}

async function imageDimensions(buffer, source) {
  const pngSignature = '89504e470d0a1a0a';
  if (buffer.length >= 24 && buffer.subarray(0, 8).toString('hex') === pngSignature) {
    return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
  }

  if (buffer.length >= 4 && buffer[0] === 0xff && buffer[1] === 0xd8) {
    let offset = 2;
    while (offset + 8 < buffer.length) {
      if (buffer[offset] !== 0xff) {
        offset += 1;
        continue;
      }
      const marker = buffer[offset + 1];
      offset += 2;
      if (marker === 0xd8 || marker === 0xd9) continue;
      if (offset + 2 > buffer.length) break;
      const length = buffer.readUInt16BE(offset);
      const isStartOfFrame = (
        (marker >= 0xc0 && marker <= 0xc3)
        || (marker >= 0xc5 && marker <= 0xc7)
        || (marker >= 0xc9 && marker <= 0xcb)
        || (marker >= 0xcd && marker <= 0xcf)
      );
      if (isStartOfFrame && offset + 7 < buffer.length) {
        return {
          width: buffer.readUInt16BE(offset + 5),
          height: buffer.readUInt16BE(offset + 3)
        };
      }
      if (length < 2) break;
      offset += length;
    }
  }

  throw new Error(`${source}: the article image must be a valid JPG or PNG.`);
}

async function loadPosts() {
  await mkdir(CONTENT_DIR, { recursive: true });
  const filenames = (await readdir(CONTENT_DIR))
    .filter((name) => name.endsWith('.md') && !name.startsWith('_'))
    .sort();
  const posts = [];
  const seenSlugs = new Set();

  for (const filename of filenames) {
    const source = path.posix.join('content/blog', filename);
    const slug = filename.slice(0, -3);
    if (!SLUG_PATTERN.test(slug)) {
      throw new Error(`${source}: filename must be a lowercase kebab-case slug.`);
    }
    if (seenSlugs.has(slug)) throw new Error(`${source}: duplicate slug "${slug}".`);
    seenSlugs.add(slug);

    const raw = await readFile(path.join(CONTENT_DIR, filename), 'utf8');
    const parsed = matter(raw);
    if (typeof parsed.data.draft !== 'boolean') {
      throw new Error(`${source}: "draft" must be true or false.`);
    }
    if (parsed.data.draft) continue;

    for (const field of ['title', 'description', 'category', 'image', 'imageAlt']) {
      if (typeof parsed.data[field] !== 'string' || !parsed.data[field].trim()) {
        throw new Error(`${source}: "${field}" is required for published posts.`);
      }
    }
    if (!Array.isArray(parsed.data.tags) || parsed.data.tags.length === 0
      || parsed.data.tags.some((tag) => typeof tag !== 'string' || !tag.trim())) {
      throw new Error(`${source}: "tags" must contain at least one non-empty tag.`);
    }
    if (!CATEGORIES[parsed.data.category]) {
      throw new Error(`${source}: "category" must be one of ${Object.keys(CATEGORIES).join(', ')}.`);
    }
    if (!IMAGE_PATTERN.test(parsed.data.image)) {
      throw new Error(`${source}: "image" must point to a JPG or PNG inside /assets/blog/.`);
    }
    if (!parsed.content.trim()) {
      throw new Error(`${source}: published posts must contain article content.`);
    }

    const published = formatDate(parsed.data.published, 'published', source);
    const updated = parsed.data.updated
      ? formatDate(parsed.data.updated, 'updated', source)
      : published;
    if (updated < published) {
      throw new Error(`${source}: "updated" cannot be earlier than "published".`);
    }

    const imagePath = path.resolve(ROOT, `.${parsed.data.image}`);
    if (!imagePath.startsWith(path.join(ROOT, 'assets', 'blog') + path.sep)) {
      throw new Error(`${source}: article image resolves outside assets/blog.`);
    }
    const imageBuffer = await readFile(imagePath).catch(() => {
      throw new Error(`${source}: article image does not exist at ${parsed.data.image}.`);
    });
    const dimensions = await imageDimensions(imageBuffer, source);
    if (dimensions.width !== 1200 || dimensions.height !== 630) {
      throw new Error(`${source}: article image must be exactly 1200×630 pixels.`);
    }

    const rendered = renderMarkdown(parsed.content, source);
    posts.push({
      slug,
      source,
      title: parsed.data.title.trim(),
      description: parsed.data.description.trim(),
      published,
      updated,
      category: parsed.data.category,
      tags: [...new Set(parsed.data.tags.map((tag) => tag.trim()))],
      image: parsed.data.image,
      imageAlt: parsed.data.imageAlt.trim(),
      imageVersion: createHash('sha256').update(imageBuffer).digest('hex').slice(0, 12),
      readingMinutes: Math.max(1, Math.ceil(wordsIn(parsed.content) / 200)),
      bodyHtml: rendered.html,
      toc: rendered.toc
    });
  }

  return posts.sort((a, b) => (
    b.published.localeCompare(a.published)
    || b.updated.localeCompare(a.updated)
    || a.slug.localeCompare(b.slug)
  ));
}

function header(active = '') {
  return `<header>
  <nav class="container nav" aria-label="Primary navigation">
    <a class="brand" href="/" aria-label="DuniaOps home"><img class="mark" src="/assets/logo-mark.png" alt="DuniaOps logo" width="59" height="32"><img class="word" src="/assets/logo-wordmark.png" alt="DuniaOps" width="69" height="15"></a>
    <button class="nav-burger" type="button" aria-expanded="false" aria-controls="primary-navigation" aria-label="Open navigation"><span></span><span></span><span></span></button>
    <ul class="nav-links" id="primary-navigation">
      <li><a href="/#services">Services</a></li>
      <li><a href="/products">Products</a></li>
      <li><a href="/#why">Why us</a></li>
      <li><a href="/#process">Process</a></li>
      <li><a href="/blog"${active === 'blog' ? ' class="active" aria-current="page"' : ''}>Blog</a></li>
      <li><a href="/#contact">Contact</a></li>
      <li><a class="btn btn-red" href="/#contact">Discuss your project</a></li>
    </ul>
  </nav>
</header>`;
}

function footer() {
  return `<footer class="foot">
  <div class="container">
    <div class="foot-grid">
      <div><span class="plate"><img class="mark" src="/assets/logo-mark.png" alt=""><img class="word" src="/assets/logo-wordmark.png" alt="DuniaOps" width="69" height="15"></span><p>Software development consultancy, delivered worldwide from London, United Kingdom.</p></div>
      <div><h4>Services</h4><ul><li><a href="/services/ai-software-development">AI-Accelerated Development</a></li><li><a href="/services/booking-and-allocation-systems">Booking &amp; Allocation Platforms</a></li><li><a href="/services/devops-and-cloud-consultancy">DevOps &amp; Cloud Consultancy</a></li><li><a href="/services/mobile-app-development">Mobile Apps</a></li><li><a href="/services/software-consultancy">Software Consultancy</a></li></ul></div>
      <div><h4>Company</h4><ul><li><a href="/products">Products</a></li><li><a href="/#why">About</a></li><li><a href="/#process">How we work</a></li><li><a href="/blog">Blog</a></li><li><a href="/#contact">Contact</a></li><li><a href="https://www.linkedin.com/company/duniaops" rel="me">LinkedIn</a></li><li><a href="/privacy">Privacy</a></li></ul></div>
    </div>
    <div class="foot-base"><span>© 2026 DuniaOps Solution and Consulting Ltd · Company no. 11173416.</span><span><a href="/feed.xml">RSS</a> · London, United Kingdom · <a href="mailto:info@duniaops.com">info@duniaops.com</a></span></div>
  </div>
</footer>`;
}

function baseHead({ title, description, canonical, robots = '', socialType = 'website', image, extra = '' }) {
  const imageUrl = image || `${SITE_URL}/assets/social-card.png?v=20260721`;
  return `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<meta name="description" content="${escapeHtml(description)}">
${robots ? `<meta name="robots" content="${escapeHtml(robots)}">\n` : ''}<link rel="canonical" href="${escapeHtml(canonical)}">
<meta property="og:title" content="${escapeHtml(title)}">
<meta property="og:description" content="${escapeHtml(description)}">
<meta property="og:type" content="${escapeHtml(socialType)}">
<meta property="og:url" content="${escapeHtml(canonical)}">
<meta property="og:image" content="${escapeHtml(imageUrl)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${escapeHtml(title)}">
<meta name="twitter:description" content="${escapeHtml(description)}">
<meta name="twitter:image" content="${escapeHtml(imageUrl)}">
<link rel="alternate" type="application/rss+xml" title="DuniaOps Blog" href="${SITE_URL}/feed.xml">
<meta name="theme-color" content="#070d17">
<link rel="icon" type="image/png" href="/assets/favicon.png?v=20260721">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="/css/site.css?v=20260723-blog">
<script src="/js/analytics.js?v=20260721" defer></script>
<script src="/js/site.js?v=20260723-blog" defer></script>
${extra}`;
}

function blogCard(post, heading = 'h2', extraClass = '') {
  const category = CATEGORIES[post.category];
  return `<article class="blog-card${extraClass ? ` ${extraClass}` : ''}">
  <a class="blog-card-image" href="/blog/${post.slug}" tabindex="-1" aria-hidden="true"><img src="${post.image}?v=${post.imageVersion}" alt="" width="1200" height="630" loading="lazy" decoding="async"></a>
  <div class="blog-card-body">
    <div class="article-meta"><span>${escapeHtml(category.label)}</span><span aria-hidden="true">·</span><time datetime="${post.published}">${displayDate(post.published)}</time><span aria-hidden="true">·</span><span>${post.readingMinutes} min read</span></div>
    <${heading}><a href="/blog/${post.slug}">${escapeHtml(post.title)}</a></${heading}>
    <p>${escapeHtml(post.description)}</p>
    <a class="more" href="/blog/${post.slug}" aria-label="Read ${escapeHtml(post.title)}">Read article</a>
  </div>
</article>`;
}

function renderBlogIndex(posts) {
  const hasPosts = posts.length > 0;
  const canonical = `${SITE_URL}/blog`;
  const description = 'Practical articles from the DuniaOps team about software development, AI-accelerated delivery, booking platforms, mobile apps, DevOps and cloud engineering.';
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Blog',
        '@id': `${canonical}#blog`,
        name: 'DuniaOps Blog',
        url: canonical,
        description,
        publisher: {
          '@type': 'Organization',
          name: 'DuniaOps Solution and Consulting Ltd',
          url: `${SITE_URL}/`,
          logo: `${SITE_URL}/assets/logo-mark.png`
        },
        blogPost: posts.map((post) => ({
          '@type': 'BlogPosting',
          headline: post.title,
          url: `${SITE_URL}/blog/${post.slug}`,
          datePublished: post.published
        }))
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE_URL}/` },
          { '@type': 'ListItem', position: 2, name: 'Blog' }
        ]
      }
    ]
  };

  const content = hasPosts
    ? `<div class="blog-grid">${posts.map((post) => blogCard(post)).join('\n')}</div>`
    : `<div class="blog-empty">
        <span class="blog-empty-icon" aria-hidden="true">✦</span>
        <h2>Practical articles are on the way</h2>
        <p>We’re preparing useful guidance on building software, applying AI responsibly, improving cloud delivery, and running dependable digital products.</p>
        <div class="blog-empty-actions"><a class="btn btn-red" href="/#contact">Discuss a project</a><a class="btn btn-outline" href="/feed.xml">Follow via RSS</a></div>
      </div>`;

  return `${GENERATED_MARKER}
<!DOCTYPE html>
<html lang="en">
<head>
${baseHead({
    title: 'DuniaOps Blog | Software, AI & DevOps Insights',
    description,
    canonical,
    robots: hasPosts ? '' : 'noindex,follow',
    extra: `<script type="application/ld+json">\n${jsonForHtml(schema)}\n</script>`
  })}
</head>
<body>
<a class="skip-link" href="#main-content">Skip to main content</a>
${header('blog')}
<main id="main-content">
  <div class="page-hero blog-hero">
    <div class="container">
      <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> / Blog</nav>
      <span class="kicker">DuniaOps Blog</span>
      <h1>Practical thinking for better software delivery</h1>
      <p class="lead">Straightforward guidance from senior engineers on software, AI, booking platforms, mobile products, DevOps and cloud operations.</p>
      <a class="rss-link" href="/feed.xml" aria-label="Follow the DuniaOps Blog via RSS">Follow via RSS <span aria-hidden="true">↗</span></a>
    </div>
  </div>
  <section class="blog-listing">
    <div class="container">${content}</div>
  </section>
</main>
${footer()}
</body>
</html>
`;
}

function relatedPostsFor(post, posts) {
  return posts
    .filter((candidate) => candidate.slug !== post.slug)
    .map((candidate) => ({
      post: candidate,
      score: (candidate.category === post.category ? 10 : 0)
        + candidate.tags.filter((tag) => post.tags.includes(tag)).length
    }))
    .sort((a, b) => b.score - a.score || b.post.published.localeCompare(a.post.published))
    .slice(0, 3)
    .map(({ post: candidate }) => candidate);
}

function renderPost(post, posts) {
  const canonical = `${SITE_URL}/blog/${post.slug}`;
  const category = CATEGORIES[post.category];
  const imageUrl = absoluteUrl(`${post.image}?v=${post.imageVersion}`);
  const related = relatedPostsFor(post, posts);
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'BlogPosting',
        '@id': `${canonical}#article`,
        mainEntityOfPage: canonical,
        headline: post.title,
        description: post.description,
        image: {
          '@type': 'ImageObject',
          url: imageUrl,
          width: 1200,
          height: 630
        },
        datePublished: post.published,
        dateModified: post.updated,
        author: {
          '@type': 'Organization',
          name: 'DuniaOps Team',
          url: `${SITE_URL}/`
        },
        publisher: {
          '@type': 'Organization',
          name: 'DuniaOps Solution and Consulting Ltd',
          url: `${SITE_URL}/`,
          logo: {
            '@type': 'ImageObject',
            url: `${SITE_URL}/assets/logo-mark.png`
          }
        },
        articleSection: category.label,
        keywords: post.tags.join(', '),
        url: canonical
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE_URL}/` },
          { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE_URL}/blog` },
          { '@type': 'ListItem', position: 3, name: post.title }
        ]
      }
    ]
  };
  const articleMeta = [
    `<span>${escapeHtml(category.label)}</span>`,
    '<span aria-hidden="true">·</span>',
    `<time datetime="${post.published}">${displayDate(post.published)}</time>`,
    '<span aria-hidden="true">·</span>',
    `<span>${post.readingMinutes} min read</span>`
  ].join('');
  const updated = post.updated !== post.published
    ? `        <p class="article-updated">Updated <time datetime="${post.updated}">${displayDate(post.updated)}</time></p>\n`
    : '';
  const toc = post.toc.length >= 2
    ? `          <nav class="article-toc" aria-labelledby="contents-title"><strong id="contents-title">In this article</strong><ol>${post.toc.map((item) => `<li><a href="#${item.id}">${escapeHtml(item.label)}</a></li>`).join('')}</ol></nav>\n`
    : '';
  const tags = post.tags.map((tag) => `<span class="article-tag">${escapeHtml(tag)}</span>`).join('');
  const shareUrl = encodeURIComponent(canonical);
  const shareTitle = encodeURIComponent(post.title);
  const relatedSection = related.length
    ? `  <section class="related-posts" aria-labelledby="related-title"><div class="container"><div class="section-head"><span class="kicker">Keep reading</span><h2 id="related-title">Related articles</h2></div><div class="blog-grid blog-grid-related">${related.map((item) => blogCard(item, 'h3')).join('\n')}</div></div></section>\n`
    : '';

  return `${GENERATED_MARKER}
<!DOCTYPE html>
<html lang="en">
<head>
${baseHead({
    title: `${post.title} | DuniaOps`,
    description: post.description,
    canonical,
    socialType: 'article',
    image: imageUrl,
    extra: `<meta property="article:published_time" content="${post.published}T00:00:00Z">
<meta property="article:modified_time" content="${post.updated}T00:00:00Z">
<meta property="article:section" content="${escapeHtml(category.label)}">
${post.tags.map((tag) => `<meta property="article:tag" content="${escapeHtml(tag)}">`).join('\n')}
<script type="application/ld+json">\n${jsonForHtml(schema)}\n</script>`
  })}
</head>
<body>
<a class="skip-link" href="#main-content">Skip to main content</a>
${header('blog')}
<main id="main-content">
  <article class="article-page">
    <header class="article-header">
      <div class="container article-header-inner">
        <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/blog">Blog</a> / ${escapeHtml(post.title)}</nav>
        <div class="article-meta">${articleMeta}</div>
        <h1>${escapeHtml(post.title)}</h1>
        <p class="article-deck">${escapeHtml(post.description)}</p>
        <div class="article-byline"><span class="article-author-mark">D</span><div><strong>DuniaOps Team</strong><span>Senior software and DevOps engineers</span></div></div>
${updated}      </div>
    </header>
    <div class="container">
      <figure class="article-hero-image"><img src="${post.image}?v=${post.imageVersion}" alt="${escapeHtml(post.imageAlt)}" width="1200" height="630"></figure>
      <div class="article-layout">
        <div class="article-main">
${toc}          <div class="article-content prose">${post.bodyHtml}</div>
          <div class="article-tags" aria-label="Article topics">${tags}</div>
          <div class="article-share" aria-labelledby="share-title">
            <strong id="share-title">Share this article</strong>
            <div>
              <a href="https://www.linkedin.com/sharing/share-offsite/?url=${shareUrl}">LinkedIn</a>
              <a href="https://twitter.com/intent/tweet?url=${shareUrl}&text=${shareTitle}">X</a>
              <a href="mailto:?subject=${shareTitle}&body=${shareUrl}">Email</a>
              <button type="button" data-copy-url="${escapeHtml(canonical)}">Copy link</button>
              <span class="copy-status" role="status" aria-live="polite"></span>
            </div>
          </div>
          <aside class="article-author-box" aria-label="About the author">
            <span class="article-author-mark">D</span>
            <div><strong>Written by the DuniaOps Team</strong><p>Senior engineers sharing practical lessons from designing, building and operating modern software.</p></div>
          </aside>
        </div>
        <aside class="article-service-cta">
          <span class="kicker">How we can help</span>
          <h2>${escapeHtml(category.ctaTitle)}</h2>
          <p>${escapeHtml(category.ctaText)}</p>
          <a class="btn btn-red" href="${category.serviceUrl}">Explore this service</a>
          <a class="article-cta-contact" href="/#contact">Discuss a project →</a>
        </aside>
      </div>
    </div>
  </article>
${relatedSection}</main>
${footer()}
</body>
</html>
`;
}

function renderFeed(posts) {
  const items = posts.map((post) => {
    const category = CATEGORIES[post.category];
    return `    <item>
      <title>${escapeXml(post.title)}</title>
      <link>${SITE_URL}/blog/${post.slug}</link>
      <guid isPermaLink="true">${SITE_URL}/blog/${post.slug}</guid>
      <pubDate>${new Date(`${post.published}T00:00:00Z`).toUTCString()}</pubDate>
      <description>${escapeXml(post.description)}</description>
      <author>info@duniaops.com (DuniaOps Team)</author>
      <category>${escapeXml(category.label)}</category>
${post.tags.map((tag) => `      <category>${escapeXml(tag)}</category>`).join('\n')}
    </item>`;
  }).join('\n');
  const lastBuildDate = posts.length
    ? `\n    <lastBuildDate>${new Date(`${posts[0].updated}T00:00:00Z`).toUTCString()}</lastBuildDate>`
    : '';
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>DuniaOps Blog</title>
    <link>${SITE_URL}/blog</link>
    <description>Practical articles about software development, AI, DevOps, cloud engineering, booking platforms and mobile products.</description>
    <language>en-gb</language>
    <atom:link href="${SITE_URL}/feed.xml" rel="self" type="application/rss+xml"/>${lastBuildDate}
${items}
  </channel>
</rss>
`;
}

function renderHomepageLatest(posts) {
  if (!posts.length) return '';
  const homepagePosts = posts.slice(0, 4);
  return `<section class="homepage-blog" aria-labelledby="latest-blog-title">
  <div class="container">
    <div class="section-head"><span class="kicker">From the blog</span><h2 id="latest-blog-title">Latest thinking from the DuniaOps team</h2><p>Practical guidance for teams building and operating modern software.</p></div>
    <div class="blog-grid blog-grid-related homepage-blog-grid">${homepagePosts.map((post, index) => blogCard(post, 'h3', index === 3 ? 'homepage-blog-card-fourth' : '')).join('\n')}</div>
    <div class="homepage-blog-more"><a class="btn btn-outline" href="/blog">View all articles</a></div>
  </div>
</section>`;
}

function renderSitemapEntries(posts) {
  if (!posts.length) return '';
  const latest = posts.reduce((value, post) => post.updated > value ? post.updated : value, posts[0].updated);
  const entries = [
    { url: '/blog', lastmod: latest, priority: '0.8', changefreq: 'weekly' },
    ...posts.map((post) => ({
      url: `/blog/${post.slug}`,
      lastmod: post.updated,
      priority: '0.7',
      changefreq: 'yearly'
    }))
  ];
  return entries.map((entry) => `  <url>
    <loc>${SITE_URL}${entry.url}</loc>
    <lastmod>${entry.lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
  </url>`).join('\n');
}

function renderRedirects(posts) {
  return [
    '/blog.html /blog 301!',
    ...posts.map((post) => `/blog/${post.slug}.html /blog/${post.slug} 301!`)
  ].join('\n');
}

function replaceSection(source, start, end, content, insertBefore = '') {
  const block = `${start}\n${content}${content ? '\n' : ''}${end}`;
  const startIndex = source.indexOf(start);
  const endIndex = source.indexOf(end);
  if ((startIndex >= 0) !== (endIndex >= 0) || (startIndex >= 0 && endIndex < startIndex)) {
    throw new Error(`Generated section markers are incomplete: ${start} / ${end}`);
  }
  if (startIndex >= 0) {
    return source.slice(0, startIndex) + block + source.slice(endIndex + end.length);
  }
  if (insertBefore && source.includes(insertBefore)) {
    return source.replace(insertBefore, `${block}\n${insertBefore}`);
  }
  return `${source.trimEnd()}\n${block}\n`;
}

async function updateGeneratedSections(posts) {
  const sitemapPath = path.join(ROOT, 'sitemap.xml');
  const sitemap = await readFile(sitemapPath, 'utf8');
  await writeFile(sitemapPath, replaceSection(
    sitemap,
    '  <!-- blog:start -->',
    '  <!-- blog:end -->',
    renderSitemapEntries(posts),
    '</urlset>'
  ));

  const redirectsPath = path.join(ROOT, '_redirects');
  const redirects = await readFile(redirectsPath, 'utf8');
  await writeFile(redirectsPath, replaceSection(
    redirects,
    '# blog:start',
    '# blog:end',
    renderRedirects(posts)
  ));

  const homepagePath = path.join(ROOT, 'index.html');
  const homepage = await readFile(homepagePath, 'utf8');
  await writeFile(homepagePath, replaceSection(
    homepage,
    '<!-- blog-latest:start -->',
    '<!-- blog-latest:end -->',
    renderHomepageLatest(posts),
    '<!-- ============ enquiry ============ -->'
  ));
}

async function removeStaleGeneratedPosts(expectedFiles) {
  await mkdir(BLOG_DIR, { recursive: true });
  for (const filename of await readdir(BLOG_DIR)) {
    if (!filename.endsWith('.html') || expectedFiles.has(filename)) continue;
    const filePath = path.join(BLOG_DIR, filename);
    const details = await stat(filePath);
    if (!details.isFile()) continue;
    const beginning = (await readFile(filePath, 'utf8')).slice(0, GENERATED_MARKER.length);
    if (beginning === GENERATED_MARKER) await unlink(filePath);
  }
}

async function validateInternalLinks(posts, generatedFiles) {
  const validRoutes = new Set(STATIC_ROUTES);
  for (const post of posts) validRoutes.add(`/blog/${post.slug}`);
  const errors = [];

  for (const filePath of generatedFiles) {
    const html = await readFile(filePath, 'utf8');
    for (const match of html.matchAll(/\b(?:href|src)="([^"]+)"/g)) {
      const value = match[1].replaceAll('&amp;', '&');
      if (/^(?:https?:|mailto:|tel:|#)/i.test(value)) continue;
      if (!value.startsWith('/')) {
        errors.push(`${path.relative(ROOT, filePath)}: generated link must be root-relative: ${value}`);
        continue;
      }
      const pathname = value.split(/[?#]/, 1)[0];
      if (pathname.startsWith('/assets/') || pathname.startsWith('/css/') || pathname.startsWith('/js/')) {
        const assetPath = path.resolve(ROOT, `.${pathname}`);
        if (!assetPath.startsWith(ROOT + path.sep)) {
          errors.push(`${path.relative(ROOT, filePath)}: unsafe asset path ${pathname}`);
          continue;
        }
        try {
          const details = await stat(assetPath);
          if (!details.isFile()) errors.push(`${path.relative(ROOT, filePath)}: missing asset ${pathname}`);
        } catch {
          errors.push(`${path.relative(ROOT, filePath)}: missing asset ${pathname}`);
        }
      } else if (!validRoutes.has(pathname)) {
        errors.push(`${path.relative(ROOT, filePath)}: broken internal link ${pathname}`);
      }
    }
  }

  if (errors.length) throw new Error(`Generated link validation failed:\n- ${errors.join('\n- ')}`);
}

async function main() {
  const posts = await loadPosts();
  await mkdir(BLOG_DIR, { recursive: true });
  const expectedPostFiles = new Set(posts.map((post) => `${post.slug}.html`));
  await removeStaleGeneratedPosts(expectedPostFiles);

  const generatedFiles = [];
  const blogIndexPath = path.join(ROOT, 'blog.html');
  await writeFile(blogIndexPath, renderBlogIndex(posts));
  generatedFiles.push(blogIndexPath);

  for (const post of posts) {
    const outputPath = path.join(BLOG_DIR, `${post.slug}.html`);
    await writeFile(outputPath, renderPost(post, posts));
    generatedFiles.push(outputPath);
  }

  const feedPath = path.join(ROOT, 'feed.xml');
  await writeFile(feedPath, renderFeed(posts));
  await updateGeneratedSections(posts);
  await validateInternalLinks(posts, generatedFiles);

  console.log(`Built the DuniaOps blog with ${posts.length} published post${posts.length === 1 ? '' : 's'}.`);
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
